### ISSUE TITLE
画像の整理

### ISSUE THREAD

**Issue by satoshicano** [fabnavi/fabnavi-app#129]
- 画像のファイル命名とか、そもそも使ってない画像の消去等をお願いしたい。

[![https://gyazo.com/3cd086a3cd96526de3c4433a0bc1a48d](https://i.gyazo.com/3cd086a3cd96526de3c4433a0bc1a48d.png)](https://gyazo.com/3cd086a3cd96526de3c4433a0bc1a48d)

**Comment by tkatsuya** [comment]
現状不必要な画像は削除しました。
