### ISSUE TITLE
[WIP] : Update ButtonとBack Buttonのレイアウト修正

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#13]
master branchにmergeされたupdate-button branchで実装された，Update ButtonとBack Buttonのレイアウトが未完成

Update ButtonはFooter Componentの下，Back ButtonはFooter Component内にある

**Comment by tkatsuya** [comment]
了解です。随時更新して行きます。
まずは更新ボタンのレイアウトについて考えて行きます。

**Comment by fmsuvM** [comment]
少し要件を追加．Detail画面やEdit画面にはNavigation Barがあるから，BackButtonは仕込めるけど， *Player画面だけは別でレイアウト設置する必要があるので注意*  
よろしくお願いします

**Comment by fmsuvM** [comment]
- [x] : Update Button Layout
- [ ] : Back Button Layout
   - [x] : Home
   - [x] : Detail
   - [x] : Edit
   - [ ] : Player 
Back Buttonはnavigation barに設置．しかしPlayer modeはNavigation Barがないため別実装の必要あり

**Comment by fmsuvM** [comment]
これは終了と判断して良い？

**Comment by tkatsuya** [comment]
update buttonとbuck buttonのレイアウトは以前に一旦終了した。

現時点でこのissueに求められていることが不明だから要件を満たしているのか判断できない。

**Comment by hrl7** [comment]
じゃあ一旦閉じて, 必要なら新しいissueを立てよう。
