### ISSUE TITLE
FooterもしくはProject Viewが中央線から少しずれている

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#132]
footerとpagination buttonを見た時に，中央がずれている事に気づいた．
footerがずれているのか，Project View(Paginatoin ButtonとかProject Cardの塊とか)がずれているのかは不明．要調査

![image](https://gyazo.com/2b5686571b3d20aaf2396b86d51b24d6)

**Comment by tkatsuya** [comment]
これはページネーションボタンの位置がずれているはず。
若干決めうち入れた気がする。

**Comment by fmsuvM** [comment]
修正お願いします

**Comment by tkatsuya** [comment]
はい。
