### ISSUE TITLE
Update Buttonの位置

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#133]
検索窓のレイアウトを適当に蘇生させたので，UdateButtonが意味の分からない位置に行ってしまっている．
早めに対処お願いします．
#123 と関係あり

[image](https://gyazo.com/454aae904ab5db1dd4344017dc4dab63.png)

**Comment by tkatsuya** [comment]
これはかなり前のcssではスクロール形式にしていた気がする。

やっておきます。

**Comment by tkatsuya** [comment]
何をどのタイミング、どう、適当にやったら、意味のわからない位置にいったのか教えてほしいです。

**Comment by tkatsuya** [comment]
とりあえず、なんとかなりそうです。
