### ISSUE TITLE
Project Description protrudes from the card frame

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#134]
各プロジェクトのdescriptionが長いとはみ出てしまう．ある程度(3行くらい？)まで来たら， 省略できるようにレイアウト調整をしてほしい

[image](https://gyazo.com/b9d7b124fa602460a88be01ac011694f.png)

**Comment by tkatsuya** [comment]
現状１文のみしか枠がないため、３行くらいきたら省略というレイアウト調整は難しい。
project-cardのサイズ変更などは別のissueになる気がするので、メッセージ省略というissueに対しては完了した？と考えられる。

PRレビューして下さい。
