### ISSUE TITLE
EditとDelete は `/` 上から出来るべきか

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#139]
現状のEditとDeleteはProject Card上でできてしまうが，Detailに行ってからできたほうがいいのではないか？
要検討

**Comment by tkatsuya** [comment]
Detailにいってから、できた方がいいという理由を述べよう。
Project Card上で操作できて良いメリットと、デメリットはなんだろう。
逆に、Detail上で操作できて良いメリットと、デメリットはなんだろう。

Project CardとDetailの両方で操作できるのも良いのでは？

**Comment by hrl7** [comment]
それぞれの操作が, Detailに行ってからできないのって不自然だなぁという気はする. 
Detailで操作できて, Cardから操作できないのは, 操作体系として自然に感じられる.
実装コストは,  Cardだけなら楽. Detail上から取り去るのも楽だと思う.
