### ISSUE TITLE
Project Edit Form Design

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#141]
存外ダサいので，余裕があったら更新したい

[Edit Form](https://gyazo.com/6dc1cdb78193b6b35c4177d7e03cc76c.png)

**Comment by tkatsuya** [comment]
これは当初のものをちょい直したくらいですねぇ…

どういうものが良いとか例があれば、やりますよ。

**Comment by fmsuvM** [comment]
GitHubのコメント入力欄とか普通にキレイな気がする．あと，項目の文字の部分にmarginが全然なかったりするので，それも直してほしい．全体的なレイアウト(雰囲気)を，Detail画面に寄せていくと良いかも？
