### ISSUE TITLE
各Component内のclassNameについて

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#21]
Component内にあるclassNameが非常にわかりづらいので修正が必要
`ProjectElement.jsx` を参照
classNameの書き換えは jsx内とscss両方必須

**Comment by fmsuvM** [comment]
最新のmergeでComponentの変更あり． `Paginator.jsx` , `ProjectCard.jsx` などに分割されたので注意

**Comment by tkatsuya** [comment]
一度機能とレイアウト完成した時にリファクタリングとして、コードを綺麗にしていきたいと考えています。

まずは各ページの最低限のレイアウトを行います。
