### ISSUE TITLE
update-buttonについて

### ISSUE THREAD

**Issue by tkatsuya** [fabnavi/fabnavi-app#22]
- このボタンは機能しているのか？

- どの状態で更新可能状態となるのか？

- 画面遷移を繰り返していると、勝手に更新されていた。

**Comment by fmsuvM** [comment]
1: 機能している
2: *Back Buttonで戻った*  時だけ新しいプロジェクトがあるか確認する
     Why?: ESCで脱出するのは以前のkey操作主体のときだったので，今回はkey操作を使わないからkey側に実装していない
3: 画面遷移 -> playerとかdetailとかと考えると，escで脱出していたのと，detail以外にはまだないことが原因として考えられる
