### ISSUE TITLE
Re-design Project Card

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#33]
Project Cardのレイアウトのズレが気になる
Titleが少し上だったり，descriptionの覧が少し右にずれていたりするので修正  

[![Project Card](https://gyazo.com/ddbae9665e5390225bfe2adc9b100ab8/raw)](https://gyazo.com/ddbae9665e5390225bfe2adc9b100ab8)

**Comment by hrl7** [comment]
フォントも気になるな。

**Comment by tkatsuya** [comment]
現状のfabnavi-appでは若干修正されていますが、このissueのゴールはどこなんですか？

**Comment by satoshicano** [comment]
現状
![screenshot from 2017-09-25 21-44-22](https://user-images.githubusercontent.com/7578069/30808879-cb4a6956-a23a-11e7-9467-e7e8ee9d87cc.png)

titleが少し上になってるのが修正されれば終わり？

**Comment by tkatsuya** [comment]
わかりました。
その点を含めて気になった点は修正します。

**Comment by satoshicano** [comment]
#98 resolved
