### ISSUE TITLE
Calibration in Player mode

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#48]
Player modeにおいて，satoshicanoさんのお陰でキー操作でページ切り替えは出来るようになった．
しかし，Calibration が出来ていないことに気づいた
29日までに実装は困難なので，これも一応キーボード操作のままにしておくかどうか
また，現状キーボード操作でも機能していない
キーボードで操作出来るようにすることが最優先であると考える

**Comment by satoshicano** [comment]
#83 resolved
