### ISSUE TITLE
ログイン前にproject-detailページが表示されない

### ISSUE THREAD

**Issue by tkatsuya** [fabnavi/fabnavi-app#49]
githubログイン前にproject-detailページに行こうとするとローディングと表示されて変化しない。
ログイン後は通常通りプロジェクトカードが表示され、ディスクリプションも見ることができている。

**Comment by fmsuvM** [comment]
また，player mode等もログインしてないと表示することができない．
強制ログイン仕様にするのが良さそう．

**Comment by satoshicano** [comment]
#resolved #92
