### ISSUE TITLE
Failed delete my project

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#53]
ログイン状態で自分のprojectをdeleteしようとすると失敗し，白い画面になる
エラーログは以下の画像
master branchにて

[![Screenshot from Gyazo](https://gyazo.com/5cd5782c25b32c020aa13e8656893389/raw)](https://gyazo.com/5cd5782c25b32c020aa13e8656893389)

**Comment by satoshicano** [comment]
#54 で解決したのでcloseします
