### ISSUE TITLE
Working Mode

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#67]
fabnaviのトップページ表示状態だと，作業シーンが撮影しづらい．
なので，画面を真っ白にする状態（Working Mode） のようなものが必要．

画面の色は実際にプロジェクタに投影して調整する（#fffだと多分眩しい？）

**Comment by satoshicano** [comment]
キャリブレーション後にページを変えると Now Loading が後ろに残ってしまう
[![Screenshot from Gyazo](https://gyazo.com/436888be759d27ebff9e1c42e05ed540/raw)](https://gyazo.com/436888be759d27ebff9e1c42e05ed540)
