### ISSUE TITLE
Starting Video in Player Mode

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#72]
Player Modeで動画を再生する際，最初が画面真っ白でクリックされないと再生されないというのは若干わかりづらい．何かしらの補助？が必要

**Comment by satoshicano** [comment]
シーケンスバーの表示などをした

![image](https://user-images.githubusercontent.com/7578069/30367404-1a5d7fa6-98a9-11e7-90ce-d822c8592564.png)
