### ISSUE TITLE
No Sound in Playing Video Projects

### ISSUE THREAD

**Issue by fmsuvM** [fabnavi/fabnavi-app#73]
iPhoneで動画を録画した際に音声が入っていない問題．
canvasに動画を1フレーム毎に描画しているのが原因．

**Comment by satoshicano** [comment]
iOSクライアント側の問題だった
解決済み
![screenshot from 2017-09-27 16-19-12](https://user-images.githubusercontent.com/7578069/30900619-ab24336c-a39f-11e7-879d-3efa4646f0f4.png)
