### ISSUE TITLE
写真のプロジェクトのサムネイルが一番最初の画像になっている

### ISSUE THREAD

**Issue by tkatsuya** [fabnavi/fabnavi-app#84]
サムネイルには完成した作品を撮影した写真にするべきだと考えられる。

**Comment by satoshicano** [comment]
@tkatsuya 現状だと最後の写真（完成した作品を撮影した写真）がサムネイルになるよう設定されてるはずなんだけど、 `サムネイルが一番最初の画像になっているプロジェクト`  がどれのことを言ってるのか教えて欲しいです

**Comment by satoshicano** [comment]
無いみたいなのでclose
